version: "3"
services:
  alura-tracker:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder_vue
    container_name: alura-tracker
    ports:
      - "8080:8080"
    networks:
      - monitoring  
    volumes:
      - .:/app


  api-teste:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder_json_server
    container_name: api-teste
    ports:
      - "5000:3000"
    networks:
      - monitoring   
    volumes:
      - .:/api-teste   


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observabilidade/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitoring

networks:
  monitoring: