version: "3"
services:
  alura-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alura-tracker
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observabilidade/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring

networks:
  monitoring: